# Generated by Django 4.2.6 on 2023-10-05 12:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='Tache',
        ),
        migrations.AlterModelOptions(
            name='tache',
            options={},
        ),
    ]
